#!/usr/bin/env python3
"""
setup_music.py — 音乐文件部署脚本

功能：
  扫描源目录的音乐文件 → 生成两份输出：
  1. MP3-TF-16P TF 卡内容：按编号命名的文件夹/文件（放真正的音乐文件）
  2. ESP32 SD 卡 music_map.txt（索引文件，记录路径到编号的映射）

用法：
  python setup_music.py <源目录> [--out-mp3 <MP3卡输出目录>] [--out-map <music_map.txt输出路径>]

  默认：
    --out-mp3  源目录下的 _mp3_output/
    --out-map  源目录下的 music_map.txt

源目录结构示例：
  music/
  ├── 周杰伦/
  │   ├── 晴天.mp3
  │   ├── 稻香.mp3
  │   └── 七里香.mp3
  ├── 轻音乐/
  │   ├── 卡农.mp3
  │   └── 致爱丽丝.mp3
  ├── 孤勇者.mp3
  └── 起风了.mp3

MP3-TF-16P 卡输出：
  _mp3_output/
  ├── 01/
  │   ├── 001晴天.mp3  (复制自 周杰伦/晴天.mp3)
  │   ├── 002稻香.mp3
  │   └── 003七里香.mp3
  ├── 02/
  │   ├── 001卡农.mp3
  │   └── 002致爱丽丝.mp3
  ├── 001孤勇者.mp3
  └── 002起风了.mp3
"""

import os
import sys
import shutil
import argparse

SUPPORTED_EXTS = {'.mp3', '.wav'}
FOLDER_MAX = 99
TRACK_MAX = 255


def rmdir_empty(path):
    """删除空目录"""
    try:
        if os.path.isdir(path) and not os.listdir(path):
            os.rmdir(path)
    except OSError:
        pass


def main():
    parser = argparse.ArgumentParser(description='音乐文件部署脚本 (MP3-TF-16P)')
    parser.add_argument('src', help='源音乐目录')
    parser.add_argument('--out-mp3', default=None,
                        help='MP3-TF-16P 卡输出目录（默认 <src>/_mp3_output/）')
    parser.add_argument('--out-map', default=None,
                        help='music_map.txt 输出路径（默认 <src>/music_map.txt）')
    args = parser.parse_args()

    src_dir = os.path.abspath(args.src)
    if not os.path.isdir(src_dir):
        print(f'错误：源目录不存在: {src_dir}')
        sys.exit(1)

    out_mp3 = args.out_mp3 or os.path.join(src_dir, '_mp3_output')
    out_map = args.out_map or os.path.join(src_dir, 'music_map.txt')

    # 清空并重建 MP3 输出目录
    if os.path.exists(out_mp3):
        shutil.rmtree(out_mp3)
    os.makedirs(out_mp3, exist_ok=True)

    map_lines = []
    folder_num = 0       # 下一个文件夹编号
    root_track = 0       # 根目录曲目计数

    # 遍历源目录
    entries = sorted(os.listdir(src_dir))
    for entry in entries:
        if entry.startswith('.') or entry.startswith('_'):
            continue

        full_path = os.path.join(src_dir, entry)

        if os.path.isdir(full_path):
            # 收集此目录下的所有音频文件
            files = sorted([
                f for f in os.listdir(full_path)
                if os.path.splitext(f)[1].lower() in SUPPORTED_EXTS
            ])
            if not files:
                continue

            folder_num += 1
            if folder_num > FOLDER_MAX:
                print(f'警告：已达到最大文件夹数 {FOLDER_MAX}，跳过 {entry}')
                continue

            if len(files) > TRACK_MAX:
                print(f'错误：文件夹 "{entry}" 有 {len(files)} 个文件，'
                      f'超过每文件夹最大 {TRACK_MAX} 首限制')
                sys.exit(1)

            # 创建编号文件夹
            folder_name = f'{folder_num:02d}'
            folder_path = os.path.join(out_mp3, folder_name)
            os.makedirs(folder_path, exist_ok=True)

            map_lines.append(f'F {entry}')

            for idx, fname in enumerate(files):
                track_num = idx + 1
                new_name = f'{track_num:03d}{fname}'
                src_file = os.path.join(full_path, fname)
                dst_file = os.path.join(folder_path, new_name)
                shutil.copy2(src_file, dst_file)
                map_lines.append(f'  M {folder_num} {track_num} {fname}')
                print(f'  [{folder_num:02d}/{track_num:03d}] {entry}/{fname}')

        elif os.path.isfile(full_path):
            ext = os.path.splitext(entry)[1].lower()
            if ext not in SUPPORTED_EXTS:
                continue

            root_track += 1
            if root_track > TRACK_MAX:
                print(f'错误：根目录文件超过 {TRACK_MAX} 首限制')
                sys.exit(1)

            new_name = f'{root_track:03d}{entry}'
            dst_file = os.path.join(out_mp3, new_name)
            shutil.copy2(full_path, dst_file)
            map_lines.append(f'M 0 {root_track} {entry}')
            print(f'  [root/{root_track:03d}] {entry}')

    if not map_lines:
        print('错误：源目录中没有找到音频文件')
        rmdir_empty(out_mp3)
        sys.exit(1)

    # 写入 music_map.txt
    map_lines.insert(0, '# music_map.txt — generated by setup_music.py')
    map_lines.insert(1, '# F <名称> = 文件夹')
    map_lines.insert(2, '# M <文件夹号> <曲目号> <名称> = 音乐文件')
    map_lines.insert(3, '# 文件夹号 0 = 根目录')
    map_lines.insert(4, '')

    with open(out_map, 'w', encoding='utf-8') as f:
        f.write('\n'.join(map_lines) + '\n')

    print(f'\n完成！')
    print(f'  MP3-TF-16P 卡内容: {out_mp3}/')
    print(f'  ESP32 SD 卡索引:   {out_map}')
    print(f'  ({folder_num} 个文件夹, {root_track} 首根目录歌曲)')
    print(f'\n使用说明：')
    print(f'  1. 把 {out_mp3}/ 里的内容复制到 MP3-TF-16P 的 TF 卡根目录')
    print(f'  2. 把 {out_map} 复制到 ESP32 SD 卡的 /music_map.txt')
    print(f'  3. 注意：Windows 下复制到 TF 卡时，文件名会被截断？用英文名最好')


if __name__ == '__main__':
    main()
